### ISSUE TITLE
Required tactician version

### ISSUE THREAD

**Issue by sagikazarmark** [thephpleague/tactician-command-events#11]
This is the first time it occurs that a plugin requires tactician to be installed. Until 1.0 version the API is subject of change thus relying on any version could cause failure.

What I propose: until 1.0 of tactician require `~0.*` (eg. `~0.3` now), so that any minor release will work. After 1.0 minor releases shouldn't be supported anymore, so that we can make sure that the plugins rely on the latest stable API.

**Comment by rdohms** [comment]
Actually i believe he should make use of the new `^` operator.
It adheres closer to SemVer and offers support for "major version zero".

If he uses `^0.3` it will not move to `0.4` automatically since MJZ releases can break backwards compatibility.
- warning: this was introduced about a month ago, so it should have worked its way to most people who are not ignoring the "please update" warning.

**Comment by sagikazarmark** [comment]
@rdohms Thanks for advice. Actually, I ended up the same thoughts.

@rosstuck anything to add?

**Comment by rosstuck** [comment]
Nope, sounds legit.

**Comment by GrahamCampbell** [comment]
Wait, so we're using `^0.3` now which means that when 0.4 is released, this version constraint still allows it, and everything breaks...

**Comment by GrahamCampbell** [comment]
> If he uses ^0.3 it will not move to 0.4 

That's not true at all...

**Comment by GrahamCampbell** [comment]
Oh wait, I see that `^` behaves differently for 0.x releases. Never mind. :)

**Comment by rdohms** [comment]
@GrahamCampbell yes.
