### ISSUE TITLE
Decorator pattern

### ISSUE THREAD

**Issue by sagikazarmark** [thephpleague/tactician-command-events#3]
I think it worth to move the conversation here from the main repo.

@rosstuck I still think this should remain a decorator. I listed some arguments in the PR. Any response to those?

**Comment by rosstuck** [comment]
To me, a decorator doesn't make any more promises about execution logic than a middleware does. In the old decorator-based system, you could easily reshuffle the point at which events were dispatched too. The point at which we invoke the next callable is the exact same as the point at which we invoke the command bus.

Further, there _are_ advantages to repositioning when the events trigger. If folks want them moved before or after a database transaction middleware opens/closes, having the event dispatching as a middleware is the only place to do that.

We could say "we encourage middleware for everything except events" but then we're recommending two different extension scenarios (plus encouraging people to create decorators again, just to work around the event trigger points).

Having to support two different extension scenarios makes everything a lot more complex, especially for framework modules/bundles/providers/whatevers. Rather than having a single option which is a list of objects or lazy loading proxies, we now also have a decorator option which is trickier to configure. Considering the entire advantage of middleware was to ease the setup process, we'd be undoing a lot of that for the sake of one plugin, which actually doesn't get stricter promises for it.

The only way we could have full control over the events, anyways, would be to build the event dispatching into the StandardCommandBus. However, even _that_ isn't 100% because we re-added the CommandBus interface so folks could just write decorators around it again.

So, ultimately, that's my entire thought process on it. It doesn't make anything actually stricter and it kinda borks the standarization process around middleware. Sorry if that comes across a bit long-winded but I've thought about it a lot the last few days and can't come to any other solution.

**Comment by sagikazarmark** [comment]
I completely understand the single extension point concerns, and partly agree with it. However I don't really understand why emitting events AFTER eg. database connection open makes sense.

I have three possible solutions for this:
- Have both/one of a middleware and a decorator solution
- Create another command bus supporting both the middleware and event driven logic
- Extend the standard command bus, so that you don't have to build the event driven logic in it (I prefer this)

(or any mixture of the above)

**Comment by rosstuck** [comment]
For the database example, imagine two different use cases like this:
- I want to dispatch the CommandExecutedEvent **after** my database transaction closes, the benefit is: this allows me to know that everything has safely dispatched and been written before I trigger any side effects.
- I want to dispatch the CommandExecutedEvent **before** my database transaction closes, the benefit is: this allows any side effects to operate within the same transaction, so that if a side effect breaks, the DB changes get rolled back too.

These are different cases with different tradeoffs, based on where we stack the events. I personally have a preference for one style, someone else has a preference for another. Tactician is meant to be a relatively unopinionated library, so we shouldn't lock someone into one solution or another. That's why I'd like the events as a middleware that we can change the order of.

Breaking down the solutions
- Have a decorator solution: as discussed means we have to have multiple types of extension points
- Have a middleware solution: obviously I'm rooting for this one :grin: 
- Create another command bus with middleware _and_ event logic: I think we'd both prefer to avoid this because of the duplication
- Extend the standard command bus: I'm heavily opposed to this, we have a lot of other ways to extend the behavior here (decorators, middleware, regular composition), inheritance should be the absolute last resort.

(if I totally had my druthers, StandardCommandBus would be just CommandBus and would be marked final :grinning: )

**Comment by sagikazarmark** [comment]
Honestly, I don't have any problem with a middleware solution.

But you have to admit that it doesn't cover ALL possible use cases. I think the before->do every logic->after is a more generic workflow than the middleware->event->middleware one. The latter gives you greater flexibility, but if you don't specifically need it, you should choose the first path. Even if it is possible to reach the same functionality, events could even be part of the core logic, so I think it is better to avoid messing with the middleware chain (pushing the event middleware, taking care of right order).

Another reason to provide an `EventableCommandBus` is to be able to rely on it and emit events from the outside world (the EventableConsumer in the queueing package is perfect example)

As I said, I am not against having both a middleware AND a command bus extension as well. I also think that inheritance is a viable way here, since event handling could even be a core logic. So I would vote for decoration < inheritance not to break the singel extension concern, but I don't mind as long as I am not forced to make event handling in a middleware.

**Comment by boekkooi** [comment]
Ok here is my two cent on the event matter. 

There is not a single event for before or after!
I have used multiple CommandBus implementation and I have used multiple types of events within them (from before,after to init, begin, flush, end, final (or whatever you name them).
Middleware allows for all these cases and due to the way it's implemented you can every easily put them in the correct order.

Also overriding a CommandBus to add functionality not core to it's responsibility is just bad OOP.

**Comment by sagikazarmark** [comment]
I didn't say I can't see the advantage of middlewares.

As I said, I think it is core functionality splitted out to make it optional. Why would it be bad OOP? Inheritance is about knowledge, which is the clear case here IMO.

**Comment by rosstuck** [comment]
@sagikazarmark I do believe that the middlewares cover all use cases that the decorators do (with the possible exception of adding an extra interface but that'd be _weird_). As you said, the middlewares are more flexible and I don't think using them for the first path really adds any extra complexity (arguably reduces it even). That also includes the idea of an EventableCommandBus. Without going off topic too much, I think PHP architecture tends to use Events as an extension point a little too often, so I'm actually okay with not shipping that in core in favor of extension via middleware.

Regarding inheritance, I posted this same link in another PR @boekkooi opened but I think many of the same points about inheritance apply here as well http://ocramius.github.io/blog/when-to-declare-classes-final/ I do think extending the command bus is a sub-optimal solution here.

@boekkooi I do think there are some use cases where events might be slightly easier, such as the original package that this was extracted from (the Bernard integration), so I don't think it's a bad thing to have as a plugin but I wouldn't want to ship it in core for the reasons I mentioned above.

**Comment by sagikazarmark** [comment]
@rosstuck I accept your arguments, and understood the way you would like to follow.

However the problem I mentioned (`EventableConsumer` in the queueing package) still exists. I think it's worst to make an assumption that you have to inject the same event emitter in both the event middleware and the eventable consumer. Without this problem I wouldn't continue this and would immediately implement the middleware. So what do you think about that. (Short description: the EventableConsumer emits a cycle event using the same emitter as the current EventableCommandBus. This way I can increase counters, etc on command events and check those on cycle event. By using middleware this would become impossible, as the consumer can no longer access the actual event emitter)

**Comment by boekkooi** [comment]
@rosstuck I agree that events are very useful and that a event middleware plugin is a great idea. So no argument there.

@sagikazarmark Correct me if I'm wrong but would you problem not be solved by adding a EventEmitter constructor argument to the `EventableConsumer` and using the same emitter as a constructor argument for the middleware?

**Comment by sagikazarmark** [comment]
@boekkooi That would solve the problem, but you can't expect or even check that the same instance is passed to both objects. Also I prefer using the emitter trait which removes the need of a constructor parameter, but allows setter injection which makes things more clear in this case.

**Comment by boekkooi** [comment]
@sagikazarmark I'm sorry but my knowledge about the domain/problem is a little lacking here regarding (`EventableConsumer` etc.) but is this not just related to the bernard plugin/middleware? or even just to your domain? 

I do get the problem that you want to be sure that both use the same event emitter but (personally) i feel this is up to the developer to make sure of. If you instantiate the classes with different event emitters it should be developers problem not the plugins problem. 
Also writing good docs and a good example would solve this for (most) devs.

**Comment by sagikazarmark** [comment]
@boekkooi yeah, sorry. It is related to the bernard plugin. But I wonder that using a DI solution it can be easily solved. We will see. I will leave this open for now and see what I can come up with.

**Comment by rosstuck** [comment]
We've talked about it before but I'm also :+1: on passing in the event emitter; there's a lot of frameworks and libraries these days that rely on getting the correct emitter and folks are pretty used to that by now. I think good setup docs for the Bernard plugin can mitigate this as well.

**Comment by sagikazarmark** [comment]
What should the `EventableCommandBus` be renamed to? Also, currently the main namespace in th package is `League\Tactician` meaning the decorator is currently in the same namespace as the main command bus. However, the other namespace in the package is `CommandEvents` which is reserved for the Event classes. So the namespace is still a question.

Any ideas?

**Comment by sagikazarmark** [comment]
Bernard related discussion moved to thephpleague/tactician-bernard-queueing#4

**Comment by sagikazarmark** [comment]
Possible naming:

`League\Tactician\CommandEvents\EventMiddleware`
`League\Tactician\CommandEvents\Event\CommandSomething`

**Comment by rosstuck** [comment]
I'd be down with `League\Tactician\CommandEvents\EventMiddleware`.

**Comment by boekkooi** [comment]
@rosstuck I'm not sure but i would sort of expect `League\Tactician\Plugins\EventMiddleware` based on the current core repo but hey that's probably just a bad idea.

**Comment by sagikazarmark** [comment]
We agreed that real plugins should go into their own namespaces which is fine. I think that `Plugins` namespace is the confusing one.

**Comment by boekkooi** [comment]
@sagikazarmark thanks for letting me know.
I'm +1 on `League\Tactician\CommandEvents\EventMiddleware`
