### ISSUE TITLE
Command Finished event

### ISSUE THREAD

**Issue by sagikazarmark** [thephpleague/tactician-command-events#9]
Command received is always emitted when there is an incoming one. This would be the "counter" event. However with both command executed and command failed it feels like an overkill.

**Comment by sagikazarmark** [comment]
What would be the situation if the command failed AND the exception is not caught?

**Comment by rosstuck** [comment]
If the command failed and the exception wasn't caught, it would bubble up and either be caught by the app's error handling (very common scenario) or it would just crash the script (which could also be intended behavior).

If your question is: should we ditch one or both of CommandExecuted/CommandFailed, I think it's worth keeping them since they target different use cases. Someone might want to push them out to separate logs or collecting stats on successes vs failures. It'd be tricky to accomplish either without having both events.

**Comment by sagikazarmark** [comment]
Yeah, I ended up with the same thoughts.
